version: "3.1"
services:
  nginx:
    networks:
      - custom-network
    image: nginx:latest
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/sites-available/default.conf
    depends_on:
      - app
  app:
    networks:
      - custom-network
      - backend
    image: node:latest
    container_name: app
    working_dir: /application
    volumes:
      - .:/application
    expose:
      - "3000"
    depends_on:
      - mysqlbd
    environment:
      - DATABASE_HOST=mysqlbd
    entrypoint: ./start_application.sh

  mysqlbd:
    networks:
      - backend
    env_file: ./.env
    container_name: mysqlbd
    image: mysql:5.7
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"
networks:
  custom-network:
    driver: bridge
  backend: